- hosts: all
  vars:
    gitHubUser: traverseda
    gitRepo: https://github.com/{{user}}/termux-android-utils.git
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
  - name: write the apache config file
    template: src=/srv/httpd.j2 dest=/etc/httpd.conf
